// Code generated by protoc-gen-rest-client. DO NOT EDIT.
// source: proto/ports/output/identity.proto

package shared_kernel

import (
	"fmt"
	"encoding/json"
)

// Identity representa o enum gerado de Identity
type Identity int32

const (
	Identity_Identity_IDENTITY_UNSPECIFIED Identity = 0
	Identity_Identity_s4s                  Identity = 1
)

func (e Identity) String() string {
	switch e {
	case Identity_Identity_IDENTITY_UNSPECIFIED:
		return "Identity_IDENTITY_UNSPECIFIED"
	case Identity_Identity_s4s:
		return "Identity_s4s"
	default:
		return "UNKNOWN"
	}
}

func (e Identity) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e *Identity) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	switch s {
	case "Identity_IDENTITY_UNSPECIFIED":
		*e = Identity_Identity_IDENTITY_UNSPECIFIED
	case "Identity_s4s":
		*e = Identity_Identity_s4s
	default:
		return fmt.Errorf("invalid Identity value %q", s)
	}
	return nil
}
