// Code generated by protoc-gen-rest-client. DO NOT EDIT.
// source: proto/ports/output/locale.proto

package shared_kernel

import (
	"fmt"
	"encoding/json"
)

// Locale representa o enum gerado de Locale
type Locale int32

const (
	Locale_LOCALE_UNSPECIFIED = 0
	Locale_pt_BR              = 1
)

func (e Locale) String() string {
	switch e {
	case Locale_LOCALE_UNSPECIFIED:
		return "Locale_LOCALE_UNSPECIFIED"
	case Locale_pt_BR:
		return "Locale_pt_BR"
	default:
		return "UNKNOWN"
	}
}

func (e Locale) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e *Locale) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	switch s {
	case "Locale_LOCALE_UNSPECIFIED":
		*e = Locale_LOCALE_UNSPECIFIED
	case "Locale_pt_BR":
		*e = Locale_pt_BR
	default:
		return fmt.Errorf("invalid Locale value %q", s)
	}
	return nil
}
