// Code generated by protoc-gen-rest-client. DO NOT EDIT.
// source: proto/ports/output/request.proto

package welcome

import (
	"encoding/json"
)

// WelcomeRequest representa o modelo de dados para WelcomeRequest
type WelcomeRequest struct {
	// The email address of the new user
	To string `json:"to" validate:"required,email"`
	// The password for the new user
	Password string `json:"password" validate:"required"`
	// The token for user verification
	Token string `json:"token" validate:"required"`
	// The name of the new user
	Name string `json:"name" validate:"required"`
	// The message group id for FIFO queues
	MessageGroupId string `json:"message_group_id" validate:"required"`
}

// String retorna uma representação em string do WelcomeRequest
func (m *WelcomeRequest) String() string {
	data, _ := json.MarshalIndent(m, "", "  ")
	return string(data)
}

// Validate valida os campos do WelcomeRequest
func (m *WelcomeRequest) Validate() error {
	// TODO: Implementar validação customizada
	return nil
}

// NewWelcomeRequest cria uma nova instância de WelcomeRequest
func NewWelcomeRequest() *WelcomeRequest {
	return &WelcomeRequest{}
}
