// Code generated by protoc-gen-rest-client. DO NOT EDIT.
// source: proto/adapters/outbound/publisher.proto

package mail

import (
	assync "github.com/tecmise/connector-lib/pkg/ports/output/assync"
	welcome "github.com/tecmise/notification-service-connector-go/pkg/ports/output/welcome"
)

import (
	"context"
)
import (
	"github.com/tecmise/connector-lib/pkg/adapters/outbound/client_sqs"
	"github.com/tecmise/connector-lib/pkg/ports/output/request"
)

type (
	EmailPublisher interface {
		WelcomeMail(ctx context.Context, req *welcome.WelcomeRequest, validations ...request.CustomValidator) (*assync.QueueTriggerResponse, error)
	}

	emailPublisher struct {
		publisher client_sqs.AssyncPublisher
	}
)

func NewEmailPublisher() EmailPublisher {
	return &emailPublisher{
		publisher: client_sqs.NewAssyncPublisher(),
	}
}

func (i *emailPublisher) WelcomeMail(ctx context.Context, req *welcome.WelcomeRequest, validations ...request.CustomValidator) (*assync.QueueTriggerResponse, error) {
	if err := request.ValidateObject(req, validations...); err != nil {
		return nil, err
	}
	return i.publisher.Publish(ctx, req, "new-user-mail.fifo", req.To, req.To)
}
