// Code generated by protoc-gen-rest-client. DO NOT EDIT.
// source: proto/adapters/outbound/publisher.proto

package mail

import (
	assync "github.com/tecmise/connector-lib/pkg/ports/output/assync"
	welcome "github.com/tecmise/notification-service-connector-go/pkg/ports/output/welcome"
)

import (
	"context"
	"github.com/tecmise/connector-lib/pkg/adapters/outbound/sqs"
)

type (
	EmailPublisher interface {
		WelcomeMail(ctx context.Context, req *welcome.WelcomeRequest) (*assync.QueueTriggerResponse, error)
	}

	emailPublisher struct {
		publisher sqs.AssyncPublisher
	}
)

func NewEmailPublisher() EmailPublisher {
	return &emailPublisher{
		publisher: sqs.NewAssyncPublisher(),
	}
}

func (i *emailPublisher) WelcomeMail(ctx context.Context, req *welcome.WelcomeRequest) (*assync.QueueTriggerResponse, error) {
	return i.publisher.Publish(ctx, assync.QueueRequest(req), "new-user-mail.fifo", req.To, req.To)
}
